# Generated by Django 3.2.9 on 2021-12-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('pages', models.IntegerField(default=None, null=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=None, null=True)),
                ('row', models.IntegerField(default=None, null=True)),
                ('column', models.IntegerField(default=None, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=19, null=True)),
                ('type', models.CharField(choices=[('Bill', 'Bill'), ('Coin', 'Coin')], max_length=4)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.book')),
            ],
        ),
    ]
