# Generated by Django 3.2.9 on 2021-12-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField(default=None, null=True)),
                ('page', models.IntegerField(default=None, null=True)),
                ('row', models.IntegerField(default=None, null=True)),
                ('column', models.IntegerField(default=None, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.IntegerField(default=None, null=True)),
                ('type', models.CharField(choices=[('Bill', 'Bill'), ('Coin', 'Coin')], max_length=4)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
