# Generated by Django 3.2.9 on 2021-12-28 15:32

from django.contrib.auth.models import Group
from django.db import migrations


class Migration(migrations.Migration):
    def create_groups(app, schema_editor):
        Group.objects.get_or_create(name="Read_Only")

    def remove_groups(apps, schema_editor):
        Group.objects.filter(name="Read_Only").delete()

    dependencies = [
        ('myapp', '0002_auto_20211210_0311'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups)
    ]
