# Generated by Django 3.2.9 on 2021-12-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211210_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='columns_per_row',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rows_per_page',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
